name: Build project

on:
    push:
      branches:
        - "**"
    pull_request:

jobs:
  build_vite:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository so the workflow has access to the code
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run the 'build' command
        run: |
            npm run build
